### ISSUE TITLE
Missing image files in diagrams folder

### ISSUE THREAD

**Issue by mikecroucher** [lawrennd/mlai2015#1]
w1_probability.ipynb contains references to files that do not exist. 

diagrams/a-first-course-in-machine-learning.jpg
diagrams/978-0-387-31073-2.png
diagrams/laplacesDeterminismFrench.png
diagrams/Pierre-Simon_Laplace.png

There are also references to a folder outside of this repo. e.g.

../../../ml/tex/diagrams/philosophicaless00lapliala.png

The combination of these issues results in notebooks that do not render correctly when looking at them on a local clone of the malai15 repo.

**Comment by lawrennd** [comment]
Thanks Mike. This now fixed.
